main : com.clashwars.cwreward.CWReward
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
depend: [CWCore]
commands:
  reward:
    description: Give a specific reward.
    usage: /<command> {player} {reward}
  randomreward:
    description: Give a random reward by category.
    usage: /<command> {player} [category]
  rewards:
    description: Give rewards by category based on percentage.
    usage: /<command> {player} [category] [force]